### ISSUE TITLE
Deprecated getAttributes()

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenu#250]
With last Twig version (1.28) I'm getting a deprecation warning:
```
Calling "getattributes" on template "knp_menu.html.twig" from template "foo.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0.
```

this is the offending line in my `foo.html.twig` file:

```html+jinja
{{ macros.attributes(attributes) }}
{# macros is from {%- import "knp_menu.html.twig" as macros -%} #}
```

**Comment by garak** [comment]
See https://github.com/symfony/symfony/issues/20568

**Comment by stof** [comment]
The templates being in KnpMenu always import macros in places using them, so they should not trigger this deprecation.

This deprecation happens when you call a macro in a template while relying on an import statement done in the parent template instead of importing them in your template.
Please check your own templates which may be using our macro

**Comment by garak** [comment]
Sorry @stof I got lost. What is the proposed solution? Should I redefine the macro in my template or what else?

**Comment by stof** [comment]
no, you should not define the macro. you should import the macro (instead of relying on the implementation detail exposing you the macro imported by the parent template in some cases)

**Comment by garak** [comment]
Well, maybe I need to to give more details on my template. Here it is:
```html+jinja
{% extends 'knp_menu.html.twig' %}
{% block item %}
    {% import "knp_menu.html.twig" as macros %}
    <li{{ macros.attributes(attributes) }}></li>
{% endblock %}
```
What should I do?

**Comment by garak** [comment]
Well, I resolved removing `{% import "knp_menu.html.twig" as macros %}` and re-defining the macro from knp_menu.html.twig in my template. It looks like a workaround, but at least it works.
If you can suggest a better solution, it would be much appreciated. Otherwise, feel free to close.
Thanks

**Comment by sgehrig** [comment]
@garak I did experience the same issue. If you're using overwritten KNP menu templates it's highly possible that you overwrite more than one block. As the macros are being used in several blocks, you need to import the macros (`{% import "knp_menu.html.twig" as macros %}`) in every block they are being used. Formerly it did work without those imports because of the reasons @stof mentioned.

I'm overwriting the `{% block item %}` block as well as the `{% block linkElement %}` block and I had to add the macro import `{% import "knp_menu.html.twig" as macros %}` to both blocks to get rid of the deprecation message.

**Comment by wouterj** [comment]
Closing this issue is not in KnpMenu and the solution for people's template is nicely explained by @sgehrig
